# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"

      - name: build client
        run: docker-compose up -d client

      - name: install dependencies
        run: |
          cd client/
          yarn
      - name: run client tests
        run: docker-compose run client yarn run test:unit

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build api
        run: docker-compose up -d client

      - name: create database
        run: docker-compose run api rake db:create

      - name: create migrations
        run: docker-compose run api rake db:migrate

      - name: run api tests
        run: docker-compose run api bundle exec rails test
      
      
      
      
#   test:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Ruby
#     # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
#     # change this to (see https://github.com/ruby/setup-ruby#versioning):
#     # uses: ruby/setup-ruby@v1
#       uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
#       with:
#         ruby-version: 2.6
#     - name: Install dependencies
#       run: bundle install
#     - name: Run tests
#       run: bundle exec rails test
